export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESSS = 'ADD_COMMENT_SUCCESSS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'


export const COMMENTS_BY_POST = 'COMMENTS_BY_POST'
export const COMMENTS_BY_POST_SUCCESSS = 'COMMENTS_BY_POST_SUCCESSS'
export const COMMENTS_BY_POST_FAILURE = 'COMMENTS_BY_POST_FAILURE'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESSS = 'LOGIN_SUCCESSS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESSS = 'LOGOUT_SUCCESSS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const USER_CURRENT = "USER_CURRENT"
