export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESSS = 'ADD_COMMENT_SUCCESSS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'


export const COMMENTS_BY_POST = 'COMMENTS_BY_POST'
export const COMMENTS_BY_POST_SUCCESSS = 'COMMENTS_BY_POST_SUCCESSS'
export const COMMENTS_BY_POST_FAILURE = 'COMMENTS_BY_POST_FAILURE'

